# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

setup_travis

platform :ios do
  lane :screenshots do 
    capture_screenshots
  end

  desc "Run application unit tests"
  lane :tests do
    run_tests(scheme: "ROMWOD", devices: ["iPhone 8"])
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "development")
    tests
    capture_screenshots
    increment_build_number(xcodeproj: "ROMWOD.xcodeproj")
    build_app(scheme: "ROMWOD")
    upload_to_testflight
  end
end
