# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis
default_platform(:ios)

platform :ios do
  lane :screenshots do 
    capture_screenshots
  end

  desc "Run application unit tests"
  lane :tests do
    run_tests(scheme: "ROMWOD", devices: ["iPhone 8"])
  end

  lane :keychain do |options|
    create_keychain(
      name: options[:name],
      password: options[:password],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end

  desc "Build Application"
  lane : do |options|

    password = SecureRandom.base64
    keychain_name = "fastlane"

    ENV["MATCH_KEYCHAIN_NAME"] = keychain_name

    ENV["MATCH_KEYCHAIN_PASSWORD"] = password
    keychain(name: keychain_name, password: password)
    scheme = "ROMWOD"

    match(type: "appstore", keychain_name: keychain_name, keychain_password: password, readonly: true)
    
    if options[:scheme]
      scheme = options.scheme
    end
    configuration = options[:configuration]
    export_method = options[:export_method]
    build_app(
      scheme: "ROMWOD",
      clean: true
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    tests
    capture_screenshots
    increment_build_number(xcodeproj: "ROMWOD.xcodeproj")
    build
    upload_to_testflight
  end
end
